# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170408_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
