# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('i', 'In Progress'), ('r', 'In review'), ('p', 'Published')], default='i', max_length=1),
        ),
    ]
